#%RAML 1.0
resourceTypes:
  Collection:
    get:
      responses:
        200:
          body:
            application/json:
              type: <<item>>[]
    post:
      body:
        application/json:
          type: <<item>>
  Member:
    get: 
      responses : 
        200 : 
          body:
            application/json:
              type: <<item>>
    delete:
      responses:
        204:
    put:
      body:
        application/json:
          type: <<item>>
  Salary:
    get:
      responses:
        200:
          body:
            application/json:
              properties:
                salary: number
              
title: My-API
version: v1
baseUri: http://localhost:3000
types:
  Employee:
    properties:
      id: number
      name: string
      salaryDollars: number

/employee:
  type: { Collection: {item : Employee} }
  /{id}:
    type: { Member: {item : Employee} }
    /salary-euro:
      type: Salary
    /salary-dollar:
      type: Salary
    
    
